config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'team', to: 'pages#team'
  get 'project', to: 'pages#project'
  get 'condominios', to: 'pages#condominios'
  get 'startups', to: 'pages#startups'
  get 'metodologia', to: 'pages#metodologia'
  get 'dashboard', to: 'pages#dashboard'
  resources :conflitos
  # resources :prospects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conflito.rb
class Conflito < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/conflitos_controller.rb
class ConflitosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def index
    @conflitos = Conflito.all
  end

  def show
    @conflito = Conflito.find(params[:id])
  end

  def new
    @conflito = Conflito.new
  end

  def create
    @conflito = Conflito.new(conflito_params)
    if @conflito.save
      redirect_to root_path
      flash[:notice] = "Mensagem enviada! Retornaremos em breve"
    else
      render 'new'
    end
  end

  def edit
    @conflito = Conflito.find(params[:id])
  end

  def update
    @conflito = Conflito.find(params[:id])
    @conflito.update(conflito_params)
    redirect_to conflito_path(@conflito)
  end

  def destroy
    @conflito = conflito.find(params[:id])
    @conflito.destroy
    redirect_to conflitos_path
  end

  private

  def conflito_params
    params.require(:conflito).permit(:name, :email, :title, :message, :subscribed, :answered)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :project, :condominios, :startups, :metodologia, :team]

  def home
  end

  def project
  end

  def metodologia
  end

  def team
  end

  def dashboard
    @conflitos = Conflito.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conflitos/create.html.erb
<h1>Conflitos#create</h1>
<p>Find me in app/views/conflitos/create.html.erb</p>

app/views/conflitos/destroy.html.erb
<h1>Conflitos#destroy</h1>
<p>Find me in app/views/conflitos/destroy.html.erb</p>

app/views/conflitos/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Entre em Contato</h1>

      <%= simple_form_for @conflito do |f| %>
        <%= f.input :name %>
        <%= f.input :email %>
        <%= f.input :title %>
        <%= f.input :message %>
        <%= f.label "Respondido?" %>
        <%= f.check_box :answered %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>

    </div>
  </div>
</div>

app/views/conflitos/index.html.erb
<h1>Conflitos#index</h1>
<p>Find me in app/views/conflitos/index.html.erb</p>

app/views/conflitos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>Envie uma mensagem</h2>
      <%= simple_form_for @conflito do |f| %>
        <%= f.input :name, label: 'Nome'%>
        <%= f.input :email %>
        <%= f.input :title, label: 'Assunto'%>
        <%= f.input :message, label: 'Mensagem' %>
        <%= f.label "Deseja receber nossos conteúdos" %>
        <%= f.check_box :subscribed %>
        <br>
        <%= f.button :submit, "Enviar Conflito", class: 'btn btn-primary' %>
      <% end %>
      <br>
    </div>
  </div>
</div>

app/views/conflitos/show.html.erb
<h1>Mensagem</h1>

<%= link_to "Back Messages", dashboard_path, class: "btn btn-primary" %>
 <%= link_to "Edit Message", edit_conflito_path(@conflito), class: "btn btn-primary" %>

<p>Nome: <%= @conflito.name %></p>
<p>Email: <%= @conflito.email %></p>
<p>Mensagem: <%= @conflito.message %></p>
<p>Subscribed: <%= @conflito.subscribed %></p>
<p>Respondida: <%= @conflito.answered %></p>

app/views/conflitos/update.html.erb
<h1>Conflitos#update</h1>
<p>Find me in app/views/conflitos/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Zona de Valor: Transformando conflitos em tração</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= render 'shared/analytics' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h2>Prospects</h2>

<div class="container">

<% link_to "Go to Prospects", root_path, class: "btn btn-success" %>

<table class="table table-bordered">
        <tbody>
          <thead>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Title</th>
            <th>Message</th>
            <th>Assinante?</th>
             <th>Respondido?</th>
          </thead>
          <% @conflitos.each do |conflito| %>
            <tr>
              <td><%= conflito.id %></td>
              <td><%= link_to conflito.name, conflito_path(conflito) %></td>
              <td><%= conflito.email %></td>
              <td><%= conflito.title %></td>
              <td><%= conflito.message %></td>
              <td><%= conflito.subscribed %></td>
              <td><%= conflito.answered %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
</div>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<%= render 'shared/value' %>
<%= render 'shared/skills' %>

app/views/pages/metodologia.html.erb
<%= render 'shared/skills' %>

app/views/pages/project.html.erb
<div class="company">
  <div class="company-title">
    <h1>Sobre o projeto</h1>
  </div>
  <div class="company-description">
    <p>Grupo de especialistas multidisciplinar com muito conhecimento no escossistema de empreendedorismo observou que muitas startups estavam encerrando suas atividades devido `a conflitos internos e com isso propõe uma metodologia para facilitação da resolução desse conflitos. </p>
  </div>
  <div class="company-picture">
    <%= image_tag "about.jpg", height: 500 %>
  </div>
  <div class="company-description">
    <p>Acreditamos que ambientes de inovação são por definição ambientes conflituosos. Porém também acreditamos que em todo conflito há uma parte positiva que pode ser transformada em crescimento e desenvolvimento da startup.</p>
    <p>Por isso, desenvolvemos uma metodologia de facilitação de resolução de conflitos para que as startups não tirem foco dos negócios, enquanto nós cuidamos das relações</p>
  </div>
</div>

app/views/pages/team.html.erb
<div id="container-mentor">
  <div class="container-mentor">
    <div class="card-mentor">
      <h2>CLAUDIA GROSMAN</h2>
      <p>Certificada pelo <strong>ADR Group (Londres), IMI, International Mediation Institute e Instituto Familiae</strong> (atual Mediativa). Integra o painel de mediadores de várias instituições nacionais e do CPR <strong>International Institute for Conflict, Prevention & Resolution (NY).</strong> Advogada com MBA no <strong>INSPER</strong>. Docente e Supervisora da Prática de Mediação no <strong>Instituto Mediativa</strong> e professora convidada do Mediare RJ. Conselheira do Centro de Solução de Disputas, CSD-PI e Diretora da Câmara de Mediação, CMed-ABPI, da Associação Brasileira de Propriedade Intelectual. Diretora da Câmara de Mediação do Instituto de Engenharia. Mentora em gestão de Conflitos da AceStartups e <strong>Membro do Conselho Alumni do Insper</strong>.</p>
    </div>

  <div class="card-mentor">
    <h2>DANI GLIKMANAS</h2>
    <p> Diretor de empreendimento de varejo (mall), especialista em <strong>design thinking</strong>, conselheiro de startups, mediador de conflitos, com profundo conhecimento em mercado financeiro, mentor na cadeira de Resoluções Eficaz de Problemas do <strong>Insper</strong>, conselheiro no <strong>IBRACEM</strong>, instituto que criou a primeira plataforma de compliance com uso de <strong>inteligência artificial</strong>, e voluntário no <strong>Chapter SP da Singularity University</strong>.</p>
    </div>
  </div>
</div>

<div id="container-mentor">
  <div class="container-mentor">
    <div class="card-mentor">
      <h2>CRISTIANE JIANG</h2>
      <p>Facilitadora gráfica, especialista em <strong>Comunicação não-violenta</strong>, administradora de empresas pela <strong>FEA-USP</strong> e <strong>mediadora de conflitos</strong>. Tem 15 anos de experiência em financeiras e bancos de varejo, onde desenvolveu softskills de <strong>escuta ativa</strong>, <strong>data science</strong> e trabalho em equipes.</p>
    </div>

    <div class="card-mentor">
    </div>
  </div>
</div>

app/views/prospects/_new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>Entre em Contato</h2>

        <%= simple_form_for @prospect do |f| %>
        <%= f.input :name %>
        <%= f.input :email %>
        <%= f.input :title %>
        <%= f.input :message %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-138080154-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-138080154-1');
</script>

app/views/shared/_banner.html.erb
<div class="banner-home" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.7) 0%, rgba(0,36,61,0.7) 50%), url('assets/diversity.jpg');">
  <div class="banner-home-content">
    <h1>Transforme conflitos em tração</h1>
    <p>Saiba como aproveitar a parte positiva dos conflitos</p>
  </div>
  <div class="call-to-action">
    <%= link_to "Tenho um Conflito", new_conflito_path, class: "btn btn-primary" %>
     <%= link_to "Quero evitar um Conflito", new_conflito_path, class: "btn btn-success" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_metadata.html.erb
<!-- Google result description-->
  <meta name="description" content="Transformando conflitos em tração: a Zona de Valor é uma rede de facilitadores de conflitos">
<!-- google end -->

<!-- facebook metadata -->
  <meta property="og:title" content="Zona de Valor - Transfomando conflitos em tração">
  <meta property="og:image" content="zv.png">
  <meta property="og:description" content="Transformando conflitos em tração: a Zona de Valor é uma rede de facilitadores de conflitos">
  <meta property="og:site_name" content="Zona de Valor"/>
<!-- facebook end -->

<!-- twitter metadata -->

<!-- twitter end -->

<!-- linkedin metadata -->

<!-- linkedin end -->

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "zv.png", width: 65 %>
  <% end %>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <% link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <% link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <% link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "O Projeto", "/project", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Metodologia", "/metodologia", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Mentores do Projeto", "/team", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Blog", "http://blog.zonadevalor.com.br/", class: "navbar-wagon-item navbar-wagon-link", target:"_blank" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <% link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <% link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
     <%= link_to "O Projeto", "/project", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Metodologia", "/metodologia", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Mentores do Projeto", "/team", class: "navbar-wagon-item navbar-wagon-link" %>
     <%= link_to "Blog", "http://blog.zonadevalor.com.br/", class: "navbar-wagon-item navbar-wagon-link", target:"_blank" %>
      <!-- Login link (when logged out) -->
      <% link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <%= link_to "O Projeto", "/project", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Metodologia", "/metodologia", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Mentores", "/team", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Blog", "https://zonadevalor.com.br/", class: "navbar-wagon-item navbar-wagon-link", target:"_blank" %>
      <!-- Login link (when logged out) -->
      <% link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
<!--         <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li> -->
      </ul>
    </div>
  </div>
</div>

app/views/shared/_skills.html.erb
<div class="head-title">
  <h2>Conflitos entre Sócios</h2>
  <p>Muitos conflitos entre sócios são causados por desalinhamento entre expectativas</p>
</div>

<div class="skills-content">

</div>

<div class="main-skills-container">
  <div class="container-skills">


    <div class="circle">
      <div class="skill-title">
        <p>Mapeie Incentivos e Necessidades</p>
      </div>
    </div>
      <i class="fas fa-arrow-right"></i>
    <div class="circle">
      <div class="skill-title">
        <p>Mapeie Stakeholders</p>
      </div>
    </div>
      <i class="fas fa-arrow-right"></i>
    <div class="circle">
      <div class="skill-title">
        <p>Construa Solução</p>
      </div>
    </div>
      <i class="fas fa-arrow-right"></i>
    <div class="circle">
      <div class="skill-title">
        <p>Foque nos Negócios</p>
      </div>
    </div>
  </div>
</div>

<div class="head-title">
  <h2>Conflitos entre Founders e Investidores</h2>
  <p>Muitos conflitos entre sócios são causados por desalinhamento de um novo stakeholder com expectativa de resultados em diferentes momentos</p>
</div>


<div class="main-skills-container">
  <div class="container-skills">


    <div class="circle">
      <div class="skill-title">
        <p>Mapeie Incentivos e Necessidades</p>
      </div>
    </div>
    <i class="fas fa-arrow-right"></i>
    <div class="circle">
      <div class="skill-title">
        <p>Mapeie Stakeholders</p>
      </div>
    </div>
    <i class="fas fa-arrow-right"></i>
    <div class="circle">
      <div class="skill-title">
        <p>Construa Solução</p>
      </div>
    </div>
    <i class="fas fa-arrow-right"></i>
    <div class="circle">
      <div class="skill-title">
        <p>Foque nos Negócios</p>
      </div>
    </div>

  </div>

</div>

app/views/shared/_value.html.erb
<div class="container">
  <div class="value-card">
    <i class="fas fa-star"></i>
    <h2><strong>Filtre o positivo</strong></h2>
    <p>O ambiente de inovação é por definição conflituoso. Saiba como aprender com ele</p>
  </div>
  <div class="value-card">
    <i class="fas fa-hand-holding-usd"></i>
    <h2><strong>Mais Eficiente</strong></h2>
    <p>Resolver de maneira inteligente agiliza a solução e evita gastos desnecessários!</p>
  </div>
  <div class="value-card">
    <i class="fas fa-smile-wink"></i>
    <h2><strong>Preserve as relações</strong></h2>
    <p>Mantenha sua atenção no que realmente é importante para seu negócio</p>
  </div>
</div>